// export const Tags = [
//   { id: 1, tag: "C" },
//   { id: 2, tag: "C++" },
//   { id: 3, tag: "Java" },
//   { id: 4, tag: "JavaScript" },
//   { id: 5, tag: "React" },
//   { id: 6, tag: "Html" },
//   { id: 7, tag: "CSS" },
//   { id: 8, tag: "Python" },
// ];

export const SearchTags = [
  "C",
  "C++",
  "Python",
  "React",
  "Java",
  "JavaScript",
  "Node JS",
  "Express",
  "Git",
  "Figma",
  "GitHub",
  "C#",
  "Django",
  "AWS",
  "Azure",
  "Google Cloud",
  "Angular",
  "Vue",
  "Canva",
  "Gatsby",
  "Next JS",
];
